let brands = [
     'Pinar',
     'Piyale',
     'Tamek',
     'Oncu',
     'Cyprus Garden',
     'Dogadan',
     'Doyum',
     'Solen',
     'Duru',
     'Eda',
     'Anatolian Garden',
     'Eva',
     'Hajdu',
     'Inci',
     'Medina Garden',
     'Nareddin Hoca',
     'Sarikiz',
     'Yeni Raki',
     'Tekirdag',
     'Efe',
     'Dede',
     'Koska',
     'Njoy',
     'Zade',
     'Bomonti',
     'Efes',
     'Kavklidere',
     'Ephesus',
     'Metelliana',
     'Selin',
     'Les ottomans',
     'Dede',
     'Andrex',
     'Freedom',
     'Cuddle',
     'Selpak',
     'Always',
     'Marigold',
     'Pjs',
     'Cif',
     'Domestos',
     'Colgate',
     'Dove',
     'Colgate',
     'Tampax',
     'TFC',
     'Tekirdag',
     'Kelloggs',
     'Big K',
     'Country Life',
     'Biona',
     'Pamir',
     'Delphi',
     'Melis',
     'Elmlea',
     'Sutat',
     'Meze',
     'Mr Brown',
     'Mr. Dips',
     'Njoy',
     'Bodrum',
     'Cypressa',
     'Eti',
     'Yayla',
     'Juss',
     'Haribo',
     'Dulcesol',
     'Cake Zone',
     'Country Fresh',
     'Dr Oetker',
     '7 Days',
     'Argeta',
     'Aheste',
     'Aytac',
     'Fini',
     'Efepasa',
     'Aynoor',
     'Basak',
     'Erikli',
     'Anthos',
     'Gazi',
     'Dalan',
     'Nestle',
     'Sofra',
     'Pamir Plus',
     'Ankara',
     'Doluca',
     'Pamukkale',
     'Cherchi',
     'Oba',
     'Beypazari',
     'Suntat',
     'Ulker',
     'Dilla',
     'Amita',
     'Party Sol.',
     'Party Sol',
     'Sohbet',
     'Tago',
     'Koka',
     'M.Birlik',
     'Dimes',
     'Haagen Dazs',
     'Maun',
     'Filiz',
     'Podravka',
     'Carex',
     'Superfresh',
     'Rainbow',
     'Sirma',
     'Watsons',
     'Familia',
     'Afghan',
     'Meray',
     'Falim',
     'Zaad',
     'Papouis',
     'Saxa',
     'Rayan',
     'Arya',
     'Klas',
     'Mis',
     'Cirio',
     'Burcu',
     'Persil',
     'Vanish',
     'Harpic',
     'Lipton',
     'Zaad',
     'Volvic',
     'Evian',
     'Frutti',
     'Tate Lyle',
     'Borsec',
     'Tamtad',
     'Mulliri Vjeter',
     'Elmarwa',
     'Hollyland',
     'Mogu Mogu',
     'Balconi',
     'Krasnystaw',
     'Bizim',
     'Kucharek',
     'Oatly',
     'Boromir',
     'Dobrogea',
     'Borovets',
     'Bagci',
     'Alfa',
     'Mulino Bianco',
     'Arpis',
     'Lays',
     'Buzdagi',
     'Lago',
     'Mitsides',
     'Chumak',
     'Koy Sefasi',
     'Prestige',
     'Alfa',
     'Krassi',
     'Sutdiyari',
     'Charalambous',
     'Laughing Cow',
     'Uludag',
     'Sanpellegrino',
     'Woogie',
     'Misko',
     'Garusana',
     'Rezet',
     'Jana',
     'Kiri',
     'Gullon',
     'Yedigun',
     'Mazedar',
     'Anjoman',
     'Freshways',
     'Dlux',
     'Duzzit',
     'Mehmet Efendi',
     'Aksam',
     'Mr Muscle',
     'Finish',
     'Fairy',
     'Senso',
     'Palmolive',
     'Mevlana',
     'Salina',
     'Cheetos',
     'Gurbet',
     'Epiros',
     'Donya',
     'Sera',
     'Hana',
     'Listerine',
     'Silver Spoon',
     'Binelli',
     'Emborg',
     'Egeturk',
     'Doritos',
     'La Mama Natura',
     'Glory',
     'Bravo',
     'Kerpi',
     'Mlekpol',
     'Anthap',
     'Safak',
     'Vitafeast',
     'Martini',
     'Blossom Hill',
     'Crodo',
     'Zahra',
     'Ivi',
     'Yudum',
     'Sleepy',
     'Raid',
     'Tadelle',
     'Stark',
     'Montana',
     'Camlica',
     'Milka',
     'B2',
     'Lezza',
     'Knorr',
     'Kervan',
     'Kerem',
     'Kaval',
     'Ozmo',
     'Jaffa',
     'Indomie',
     'Hamidiye',
     'Maretti',
     'Didi',
     'Aycan',
     'Helen Mykonos',
     'Istanbul',
     'Dolce Vita',
     'Corona',
     'Larissa',
     'Sarelle',
     'Melissa',
     'Natueren',
     'Unibaby',
     'Benson & Hedges',
     'Kinder',
     'Ozyorem',
     'Esin',
     'Marmaris',
     'Tempo',
     'Nasreddin Hoca',
     'Ribena',
     'Yuva',
     'Rica',
     'Haydi',
     'Madinah Delight',
     'Medovina',
     'Tadim',
     'Kellogg',
     'Luppo',
     'Heera',
     'Daz',
     'Febreze',
     'Glade',
     'Sealapack',
     'Bacofoil',
     'Abu Alabed',
     'Alpen',
     'Quaker',
     'Lizi',
     'Dorset Cereal',
     'Yakut',
     'Campo Viejo',
     'Engizek',
     'Fulya',
     'Gusto',
     `Mrs B'S`,
     'Zwan',
     'Alnakhil',
     'Tat',
     'Yorem',
     'Basra',
     'Billur',
     'Violife',
     'Delta',
     'Bojentsi',
     'Puck',
     'Henna',
     'Delta',
     'Rodoula',
     'Luxlait',
     'Kyknos',
     'La Molisana',
     'Tilda',
     'Hayat'
]

export default brands